### ISSUE TITLE
v5 compatiblity?

### ISSUE THREAD

**Issue by delz-dev** [beatwiz/statamic-entry-export-pdf#3]
Hi, any chance to see v5 compatibility update?
Would be great :-)

**Comment by beatwiz** [comment]
> Hi, any chance to see v5 compatibility update? Would be great :-)

Sure thing! I'll do it over the weekend. Please hang in there. :)

**Comment by beatwiz** [comment]
released 1.0.6 with statamic 5.0 support. cheers!

**Comment by delz-dev** [comment]
yay! Great, thanks for the super fast update 👍
